const pizzaData = [
  {
    name: "onion capsicum",
    price: "109",
    description: "Our starter pizza made with fresh onions and capsicum",
    image: "https://img.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg?w=2000",
    group: "toppings",
    featured: true,
  },
  {
    name: "onion pizza",
    price: "59",
    description: "Our starter pizza made with fresh onions",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEAk3u0uSc8chNkWC922dBqBFOr711hKK6-fmQNhTDmWcDzrjjumqBWo6fXSFFBG2lJSo&usqp=CAU",
    group: "toppings",
    featured: true,
  },
  {
    name: "capsicum pizza",
    price: "69",
    description: "Our starter pizza made with fresh capsicum",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoep7rIvqP4e8R1TPIP3rUu2KXee6Sp_9enQ&usqp=CAU",
    group: "toppings",
    featured: false,
  },
  {
    name: "mushroom",
    price: "69",
    description: "Our starter pizza made with fresh mushroooms",
    image: "https://gourmetdoneskinny.com/wp-content/uploads/2019/02/Wild-Mushroom-Slices-with-wine.jpg",
    group: "toppings",
    featured: false,
  },
  {
    name: "onion capsicum",
    price: "109",
    description: "Our starter pizza made with fresh onions and capsicum",
    image: "https://img.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg?w=2000",
    group: "toppings",
    featured: true,
  },
  {
    name: "onion pizza",
    price: "59",
    description: "Our starter pizza made with fresh onions",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEAk3u0uSc8chNkWC922dBqBFOr711hKK6-fmQNhTDmWcDzrjjumqBWo6fXSFFBG2lJSo&usqp=CAU",
    group: "toppings",
    featured: true,
  },
  {
    name: "capsicum pizza",
    price: "69",
    description: "Our starter pizza made with fresh capsicum",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoep7rIvqP4e8R1TPIP3rUu2KXee6Sp_9enQ&usqp=CAU",
    group: "toppings",
    featured: false,
  },
  {
    name: "mushroom",
    price: "69",
    description: "Our starter pizza made with fresh mushroooms",
    image: "https://gourmetdoneskinny.com/wp-content/uploads/2019/02/Wild-Mushroom-Slices-with-wine.jpg",
    group: "toppings",
    featured: false,
  },
  {
    name: "onion capsicum",
    price: "109",
    description: "Our starter pizza made with fresh onions and capsicum",
    image: "https://img.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg?w=2000",
    group: "toppings",
    featured: true,
  },
  {
    name: "onion pizza",
    price: "59",
    description: "Our starter pizza made with fresh onions",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEAk3u0uSc8chNkWC922dBqBFOr711hKK6-fmQNhTDmWcDzrjjumqBWo6fXSFFBG2lJSo&usqp=CAU",
    group: "toppings",
    featured: true,
  },
  {
    name: "capsicum pizza",
    price: "69",
    description: "Our starter pizza made with fresh capsicum",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoep7rIvqP4e8R1TPIP3rUu2KXee6Sp_9enQ&usqp=CAU",
    group: "toppings",
    featured: false,
  },
  {
    name: "mushroom",
    price: "69",
    description: "Our starter pizza made with fresh mushroooms",
    image: "https://gourmetdoneskinny.com/wp-content/uploads/2019/02/Wild-Mushroom-Slices-with-wine.jpg",
    group: "toppings",
    featured: false,
  },
  {
    name: "onion capsicum",
    price: "109",
    description: "Our starter pizza made with fresh onions and capsicum",
    image: "https://img.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg?w=2000",
    group: "toppings",
    featured: true,
  },
  {
    name: "onion pizza",
    price: "59",
    description: "Our starter pizza made with fresh onions",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEAk3u0uSc8chNkWC922dBqBFOr711hKK6-fmQNhTDmWcDzrjjumqBWo6fXSFFBG2lJSo&usqp=CAU",
    group: "toppings",
    featured: true,
  },
  {
    name: "capsicum pizza",
    price: "69",
    description: "Our starter pizza made with fresh capsicum",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoep7rIvqP4e8R1TPIP3rUu2KXee6Sp_9enQ&usqp=CAU",
    group: "toppings",
    featured: false,
  },
  {
    name: "mushroom",
    price: "69",
    description: "Our starter pizza made with fresh mushroooms",
    image: "https://gourmetdoneskinny.com/wp-content/uploads/2019/02/Wild-Mushroom-Slices-with-wine.jpg",
    group: "toppings",
    featured: false,
  },
 
];

export default pizzaData